replicaCount: 2
image:
  repository: asia-southeast1-docker.pkg.dev/smma-final-build/orean-images/orean-frontend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
probes:
  readiness:
    path: /
    port: 3000
  liveness:
    path: /
    port: 3000
