FROM node:20-slim

RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y ffprobe && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json .

RUN npm ci --omit=dev

COPY prisma/schema.prisma prisma/schema.prisma.

RUN npx prisma generate

COPY src/ ./src/

RUN npm run build

RUN addgroup --system appgroup && \
    adduser --system --shell /bin/false --no-create-home --ingroup appgroup appuser

USER appuser

EXPOSE 8080

CMD ["node","dist/server.js"]