on:
    pull_request:
        branches: dev, staging, main

jobs:
    lint-and-typecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: cd backend && npm ci
            - run: cd backend && pnx tsc --noEmit
            - run: cd orean-web && npm ci
            - run: cd orean-web && npm run lint

    dcoker-build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Build backend
              run: docker build ./backend -t test-backend.
            - name: Build frontend
              run: docker build ./orean-web -t test-frontend.
